### ISSUE TITLE
Order Pizza

### ISSUE THREAD

**Issue by TomazMartins** [fabraz/gepetohut#1]
# Order Pizza
## User Story

_I, as a customer, I want to order pizza online, to have a simpler way to request a pizza._
(_Eu,como cliente, quero pedir pizza online, para ter uma forma mais simples de solicitar uma pizza._)
## Tasks

[Once the User Story is selected to enter the team backlog tasks must be derived].
- [ ] Task one.
- [ ] Task two.
- [ ] Task three.

**Comment by josepedro** [comment]
I implemented sending of data order with GET Restful, passing parameters in URL. I think is better do it with POST.
