### ISSUE TITLE
Maintain Employee

### ISSUE THREAD

**Issue by TomazMartins** [fabraz/gepetohut#10]
# Maintain Employee
## User Story

_I, as owner of the pizzeria, I want to keep employee to take control of the employees of my establishment._
(_Eu, como dono da pizzaria, eu quero manter funcionário para ter controle dos funcionários de meu estabelecimento._)
## Tasks

[Once the User Story is selected to enter the team backlog tasks must be derived].
- [x] Implements CRUD;
  - OBS:
    - implements of Array< string > in phone attribute not possible (bash: string: not found). So I put phone as string only.
- [x] Implements relation 1 to n between Restaurants and Emloyers;
- [x] Adding field to add restaurant of employee and adding employee in restaurant;
- [x] Test.

**Comment by josepedro** [comment]
Done!
