### ISSUE TITLE
Fechar pedido (quando o status estiver em "entregue" na tela do cliente)

### ISSUE THREAD

**Issue by josepedro** [fabraz/gepetohut#39]

**Comment by Thaiane** [comment]
Está issue está associada à issue Check Status of Pizza #2.
Como é interessante que mantenha-se um histórico dos pedidos, até para a segurança da GepetoHut, caso alguém alegue não ter recebido ainda o pedido.

Como já há a checagem de status que já atualiza o status automaticamente conforme o status das pizzas, então pode-se considerar que o pedido é fechado quando o status dele é entregue.

Por isso, vou fechar o pedido.
Caso alguém acredite que deve ser reaberto sinta-se à vontade.
